# Generated by Django 2.2 on 2019-04-07 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('todo', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
